// The module 'vscode' contains the VS Code extensibility API
// Import the module and reference it with the alias vscode in your code below
import * as vscode from 'vscode';

// this method is called when your extension is activated
// your extension is activated the very first time the command is executed
export function activate(context: vscode.ExtensionContext) {
	
	// Use the console to output diagnostic information (console.log) and errors (console.error)
	// This line of code will only be executed once when your extension is activated
	console.log('Congratulations, your extension "acpihelper" is now active!');

	// The command has been defined in the package.json file
	// Now provide the implementation of the command with registerCommand
	// The commandId parameter must match the command field in package.json
	let disposable = vscode.commands.registerCommand('acpihelper.Help', () => {
		// The code you place here will be executed every time your command is executed
		// Display a message box to the user
		vscode.window.showInformationMessage('Hello World from AcpiHelper!');
	});

	vscode.languages.registerHoverProvider('EASL', {
		provideHover(document, position, token) {
			const range = document.getWordRangeAtPosition(position);
			const word = document.getText(range);
			let strTxt: string = GetPreDefineObjIndex(word);
			if (strTxt != "")
			{
				return new vscode.Hover(strTxt);
			}
		}
 	});


	context.subscriptions.push(disposable);
}

function GetPreDefineObjIndex(STxt: string) :string {
    let PreDefineName: string[] = [
		"_ACx", "_ADR", "_AEI", "_ALC", 
		"_ALI", "_ALN", "_ALP", "_ALR", 
		"_ALT", "_ALx", "_ART", "_ASI", 
		"_ASZ", "_ATT", "_BAS", "_BBN", 
		"_BCL", "_BCM", "_BCT", "_BDN", 
		"_BIF", "_BIX", "_BLT", "_BM", 
		"_BMA", "_BMC", "_BMD", "_BMS", 
		"_BPC", "_BPS", "_BPT", "_BQC", 
		"_BST", "_BTH", "_BTM", "_BTP", 
		"_CBA", "_CBR", "_CCA", "_CDM", 
		"_CID", "_CLS", "_CPC", "_CRS", 
		"_CRT", "_CSD", "_CST", "_CWS", 
		"_DBT", "_DCK", "_DCS", "_DDC", 
		"_DDN", "_DEC", "_DEP", "_DGS", 
		"_DIS", "_DLM", "_DMA", "_DOD", 
		"_DOS", "_DPL", "_DRS", "_DSD", 
		"_DSM", "_DSS", "_DSW", "_DTI", 
		"_Exx", "_EC", "_EDL", "_EJD", 
		"_EJx", "_END", "_EVT", "_FDE", 
		"_FDI", "_FDM", "_FIF", "_FIT", 
		"_FIX", "_FLC", "_FPS", "_FSL", 
		"_FST", "_GAI", "_GCP", "_GHL", 
		"_GL", "_GLK", "_GPD", "_GPE", 
		"_GRA", "_GRT", "_GSB", "_GTF", 
		"_GTM", "_GWS", "_HE", "_HID", 
		"_HMA", "_HOT", "_HPP", "_HPX", 
		"_HRV", "_IFT", "_INI", "_INT", 
		"_IOR", "_IRC", "_Lxx", "_LCK", 
		"_LEN", "_LID", "_LIN", "_LL", 
		"_LPI", "_LSI", "_LSR", "_LSW", 
		"_MAF", "_MAT", "_MAX", "_MBM", 
		"_MEM", "_MIF", "_MIN", "_MLS", 
		"_MOD", "_MSG", "_MSM", "_MTL", 
		"_MTP", "_NTT", "_OFF", "_ON", 
		"_OS", "_OSC", "_OSI", "_OST", 
		"_PAI", "_PAR", "_PCL", "_PCT", 
		"_PDC", "_PDL", "_PHA", "_PIC", 
		"_PIF", "_PIN", "_PLD", "_PMC", 
		"_PMD", "_PMM", "_POL", "_PPC", 
		"_PPE", "_PPI", "_PR", "_PR0", 
		"_PR1", "_PR2", "_PR3", "_PRE", 
		"_PRL", "_PRR", "_PRS", "_PRT", 
		"_PRW", "_PS0", "_PS1", "_PS2", 
		"_PS3", "_PSC", "_PSD", "_PSE", 
		"_PSL", "_PSR", "_PSS", "_PSV", 
		"_PSW", "_PTC", "_PTP", "_PTS", 
		"_PUR", "_PXM", "_Qxx", "_RBO", 
		"_RBW", "_RDI", "_REG", "_REV", 
		"_RMV", "_RNG", "_ROM", "_RST", 
		"_RT", "_RTV", "_RW", "_RXL", 
		"_S0", "_S1", "_S2", "_S3", 
		"_S4", "_S5", "_S1D", "_S2D", 
		"_S3D", "_S4D", "_S0W", "_S1W", 
		"_S2W", "_S3W", "_S4W", "_SB", 
		"_SBS", "_SCP", "_SDD", "_SEG", 
		"_SHL", "_SHR", "_SI", "_SIZ", 
		"_SLI", "_SLV", "_SPD", "_SPE", 
		"_SRS", "_SRT", "_SRV", "_SST", 
		"_STA", "_STB", "_STM", "_STP", 
		"_STR", "_STV", "_SUB", "_SUN", 
		"_SWS", "_T_x", "_TC1", "_TC2", 
		"_TDL", "_TFP", "_TIP", "_TIV", 
		"_TMP", "_TPC", "_TPT", "_TRA", 
		"_TRS", "_TRT", "_TSD", "_TSF", 
		"_TSN", "_TSP", "_TSS", "_TST", 
		"_TTP", "_TTS", "_TXL", "_TYP", 
		"_TZ", "_TZD", "_TZM", "_TZP", 
		"_UID", "_UPC", "_UPD", "_UPP", 
		"_VEN", "_VPO", "_WAK", "_WPC", 
		"_WPP", "_Wxx", 
		"PNP0C08", "PNP0A05", 
		"PNP0A06", "PNP0C09", 
		"PNP0C0A", "PNP0C0B", 
		"PNP0C0C", "PNP0C0D", 
		"PNP0C0E", "PNP0C0F", 
		"PNP0C80", "ACPI0001", 
		"ACPI0002", "ACPI0003", 
		"ACPI0004", "ACPI0005", 
		"ACPI0006", "ACPI0007", 
		"ACPI0008", "ACPI0009", 
		"ACPI000A", "ACPI000B", 
		"ACPI000C", "ACPI000D", 
		"ACPI000E", "ACPI000F", 
		"ACPI0010", "ACPI0011", 
		"ACPI0012", "ACPI0013", 
		"ACPI0014", "ACPI0015", 
		"ACPI0016"
		];
		
	let PreDefNameHelpStr: string[] = [
		"Active Cooling – returns the active cooling policy threshold values.", 
		"Address: (1) returns the address of a device on its parent bus. (2) returns a unique ID for the display output device. (3) resource descriptor field.", 
		"Designates those GPIO interrupts that shall be handled by OSPM as ACPI events.", 
		"Ambient Light Chromaticity – returns the ambient light color chromaticity.", 
		"Ambient Light Illuminance – returns the ambient light brightness.", 
		"Alignment – base alignment, resource descriptor field.", 
		"Ambient Light Polling – returns the ambient light sensor polling frequency.", 
		"Ambient Light Response – returns the ambient light brightness to display brightness mappings.", 
		"Ambient Light Temperature – returns the ambient light color temperature.", 
		"Active List – returns a list of active cooling device objects.", 
		"Active cooling Relationship Table – returns thermal relationship information between platform devices and fan devices.", 
		"Address Space Id – resource descriptor field.", 
		"Access Size – resource descriptor field.", 
		"Type-Specific Attribute – resource descriptor field.", 
		"Base Address – range base address, resource descriptor field.", 
		"Bios Bus Number – returns the PCI bus number returned by the platform firmware.", 
		"Brightness Control Levels – returns a list of supported brightness control levels.", 
		"Brightness Control Method – sets the brightness level of the display device.", 
		"Battery Charge Time – returns time remaining to complete charging battery.", 
		"Bios Dock Name – returns the Dock ID returned by the platform firmware.", 
		"Battery Information – returns a Control Method Battery information block.", 
		"Battery Information Extended – returns a Control Method Battery extended information block.", 
		"Battery Level Threshold – set battery level threshold preferences.", 
		"Bus Master – resource descriptor field.", 
		"Battery Measurement Averaging Interval – Sets battery measurement averaging interval.", 
		"Battery Maintenance Control – Sets battery maintenance and control features.", 
		"Battery Maintenance Data – returns battery maintenance, control, and state data.", 
		"Battery Measurement Sampling Time – Sets the battery measurement sampling time.", 
		"Battery Power Characteristics", 
		"Battery Power State", 
		"Battery Power Threshold", 
		"Brightness Query Current – returns the current display brightness level.", 
		"Battery Status – returns a Control Method Battery status block.", 
		"Battery Throttle Limit - specifies the thermal throttle limit of battery for the firmware when engaging charging.", 
		"Battery Time – returns the battery runtime.", 
		"Battery Trip Point – sets a Control Method Battery trip point.", 
		"Configuration Base Address – returns the base address of the MMIO range corresponding to the Enhanced Configuration Access Mechanism for a PCI Express or Compute Express Link host bus. The full description for the _CBA object resides in the PCI Firmware Specification. A reference to that specification is found in the “Links to ACPI-Related Documents” (http://uefi.org/acpi) under the heading “PCI SIG”.", 
		"CXL Host Bridge Register Info", 
		"Cache Coherency Attribute – specifies whether a device and its descendants support hardware managed cache coherency.", 
		"Clock Domain – returns a logical processor’s clock domain identifier.", 
		"Compatible ID – returns a device’s Plug and Play Compatible ID list.", 
		"Class Code – supplies OSPM with the PCI-defined class, subclass and programming interface for a device. Optional.", 
		"Continuous Performance Control – declares an interface that allows OSPM to transition the processor into a performance state based on a continuous range of allowable values.", 
		"Current Resource Settings – returns the current resource settings for a device.", 
		"Critical Temperature – returns the shutdown critical temperature.", 
		"C State Dependencies – returns a list of C-state dependencies.", 
		"C States – returns a list of supported C-states.", 
		"Clear Wake Status – Clears the wake status of a Time and Alarm Control Method Device.", 
		"Debounce Timeout -Debounce timeout setting for a GPIO input connection, resource descriptor field", 
		"Dock – sets docking isolation. Presence indicates device is a docking station.", 
		"Display Current Status – returns status of the display output device.", 
		"Display Data Current – returns the EDID for the display output device.", 
		"Dos Device Name – returns a device logical name.", 
		"Decode – device decoding type, resource descriptor field.", 
		"Operation Region Dependencies – evaluates to a package and designates device objects that OSPM should assign a higher priority in start ordering due to future operation region accesses.", 
		"Display Graphics State – returns the current state of the output device.", 
		"Disable – disables a device.", 
		"Device Lock Mutex- Designates a mutex as a Device Lock.", 
		"Direct Memory Access – returns a device’s current resources for DMA transactions.", 
		"Display Output Devices – enumerate all devices attached to the display adapter.", 
		"Disable Output Switching – sets the display output switching mode.", 
		"Device Selection Polarity - The polarity of the Device Selection signal on a SPISerialBus connection, resource descriptor field", 
		"Drive Strength – Drive strength setting for a GPIO output connection, resource descriptor field", 
		"Device Specific Data– returns device-specific information.", 
		"Device Specific Method – executes device-specific functions.", 
		"Device Set State – sets the display device state.", 
		"Device Sleep Wake – sets the sleep and wake transition states for a device.", 
		"Device Temperature Indication – conveys native device temperature to the platform.", 
		"Edge GPE – method executed as a result of a general-purpose event.", 
		"Embedded Controller – returns EC offset and query information.", 
		"Eject Device List – returns a list of devices that are dependent on a device (docking).", 
		"Ejection Dependent Device – returns the name of dependent (parent) device (docking).", 
		"Eject – begin or cancel a device ejection request (docking).", 
		"Endian-ness – Endian orientation of a UART SerialBus connection, resource descriptor field", 
		"Event Method - Event method for GPIO-signaled events numbered larger than 255.", 
		"Floppy Disk Enumerate – returns floppy disk configuration information.", 
		"Floppy Drive Information – returns a floppy drive information block.", 
		"Floppy Drive Mode – sets a floppy drive speed.", 
		"Fan Information – returns fan device information.", 
		"Firmware Interface Table - returns a list of NFIT Structures.", 
		"Fixed Register Resource Provider – returns a list of devices that implement FADT register blocks.", 
		"Flow Control – Flow Control mechanism for a UART SerialBus connection, resource descriptor field", 
		"Fan Performance States – returns a list of supported fan performance states.", 
		"Fan Set Level – Control method that sets the fan device’s speed level (performance state).", 
		"Fan Status – returns current status information for a fan device.", 
		"Get Averaging Interval – returns the power meter averaging interval.", 
		"Get Capabilities – Returns the capabilities of a Time and Alarm Control Method Device", 
		"Get Hardware Limit – returns the hardware limit enforced by the power meter.", 
		"Global Lock – OS-defined Global Lock mutex object.", 
		"Global Lock – returns a device’s Global Lock requirement for device access.", 
		"Get Post Data – returns the value of the VGA device that will be posted at boot.", 
		"General Purpose Events: (1) predefined Scope (_GPE). (2) Returns the SCI interrupt associated with the Embedded Controller.", 
		"Granularity – address space granularity, resource descriptor field.", 
		"Get Real Time – Returns the current time from a Time and Alarm Control Method Device.", 
		"Global System Interrupt Base – returns the GSB for a I/O APIC device.", 
		"Get Task File – returns a list of ATA commands to restore a drive to default state.", 
		"Get Timing Mode – returns a list of IDE controller timing information.", 
		"Get Wake Status – Gets the wake status of a Time and Alarm Control Method Device.", 
		"High-Edge – interrupt triggering, resource descriptor field.", 
		"Hardware ID – returns a device’s Plug and Play Hardware ID.", 
		"Heterogeneous Memory Attributes - returns a list of HMAT structures.", 
		"Hot Temperature – returns the critical temperature for sleep (entry to S4).", 
		"Hot Plug Parameters – returns a list of hot-plug information for a PCI device.", 
		"Hot Plug Parameter Extensions – returns a list of hot-plug information for a PCI device. Supersedes _HPP.", 
		"Hardware Revision– supplies OSPM with the device’s hardware revision. Optional.", 
		"IPMI Interface Type. See the Intelligent Platform Management Interface Specification at “Links to ACPI-Related Documents” (http://uefi.org/acpi) under the heading “Server Platform Management Interface Table”.", 
		"Initialize – performs device specific initialization.", 
		"Interrupts – interrupt mask bits, resource descriptor field.", 
		"IO Restriction – IO restriction setting for a GPIO IO connection, resource descriptor field", 
		"Inrush Current – presence indicates that a device has a significant inrush current draw.", 
		"Level GPE – Control method executed as a result of a general-purpose event.", 
		"Lock – locks or unlocks a device (docking).", 
		"Length – range length, resource descriptor field.", 
		"Lid – returns the open/closed status of the lid on a mobile system.", 
		"Lines in Use - Handshake lines in use in a UART SerialBus connection, resource descriptor field", 
		"Low Level – interrupt polarity, resource descriptor field.", 
		"Low Power Idle States – returns the list of low power idle states supported by a processor or processor container.", 
		"Label Storage Information – Returns information about the Label Storage Area associated with the NVDIMM object, including its size.", 
		"Label Storage Read – Returns label data from the Label Storage Area of the NVDIMM object.", 
		"Label Storage Write – Writes label data in to the Label Storage Area of the NVDIMM object.", 
		"Maximum Address Fixed – resource descriptor field.", 
		"Multiple Apic Table Entry – returns a list of Interrupt Controller Structures.", 
		"Maximum Base Address – resource descriptor field.", 
		"Memory Bandwidth Monitoring Data – returns bandwidth monitoring data for a memory device.", 
		"Memory Attributes – resource descriptor field.", 
		"Minimum Address Fixed – resource descriptor field.", 
		"Minimum Base Address – resource descriptor field.", 
		"Multiple Language String – returns a device description in multiple languages.", 
		"Mode –Resource descriptor field", 
		"Message – sets the system message waiting status indicator.", 
		"Memory Set Monitoring – sets bandwidth monitoring parameters for a memory device.", 
		"Minimum Throttle Limit – returns the minimum throttle limit of a specific thermal.", 
		"Memory Type – resource descriptor field.", 
		"Notification Temperature Threshold – returns a threshold for device temperature change that requires platform notification.", 
		"Off – sets a power resource to the off state.", 
		"On – sets a power resource to the on state.", 
		"Operating System – returns a string that identifies the operating system.", 
		"Operating System Capabilities – inform AML of host features and capabilities.", 
		"Operating System Interfaces – returns supported interfaces, behaviors, and features.", 
		"Ospm Status Indication – inform AML of event processing status.", 
		"Power Averaging Interval – sets the averaging interval for a power meter.", 
		"Parity – Parity for a UART SerialBus connection, resource descriptor field", 
		"Power Consumer List – returns a list of devices powered by a power source.", 
		"Performance Control – returns processor performance control and status registers.", 
		"Processor Driver Capabilities – inform AML of processor driver capabilities.", 
		"P-state Depth Limit – returns the lowest available performance P-state.", 
		"Clock Phase – Clock phase for a SPISerialBus connection, resource descriptor field", 
		"PIC – inform AML of the interrupt model in use.", 
		"Power Source Information – returns a Power Source information block.", 
		"Pin List – List of GPIO pins described, resource descriptor field.", 
		"Physical Location of Device  – returns a device’s physical location information.", 
		"Power Meter Capabilities – returns a list of Power Meter capabilities info.", 
		"Power Metered Devices – returns a list of devices that are measured by the power meter device.", 
		"Power Meter Measurement – returns the current value of the Power Meter.", 
		"Polarity – Resource descriptor field", 
		"Performance Present Capabilites – returns a list of the performance states currently supported by the platform.", 
		"Polling for Platform Error – returns the polling interval to retrieve Corrected Platform Error information.", 
		"Pin Configuration – Pin configuration for a GPIO connection, resource descriptor field", 
		"Processor – predefined scope for processor objects.", 
		"Power Resources for D0 – returns a list of dependent power resources to enter state D0 (fully on).", 
		"Power Resources for D1 – returns a list of dependent power resources to enter state D1.", 
		"Power Resources for D2 – returns a list of dependent power resources to enter state D2.", 
		"Power Resources for D3hot – returns a list of dependent power resources to enter state D3hot.", 
		"Power Resources for Enumeration - Returns a list of dependent power resources to enumerate devices on a bus.", 
		"Power Source Redundancy List – returns a list of power source devices in the same redundancy grouping.", 
		"Power Resource for Reset – executes a reset on the associated device or devices.", 
		"Possible Resource Settings – returns a list of a device’s possible resource settings.", 
		"Pci Routing Table – returns a list of PCI interrupt mappings.", 
		"Power Resources for Wake – returns a list of dependent power resources for waking.", 
		"Power State 0 – sets a device’s power state to D0 (device fully on).", 
		"Power State 1 – sets a device’s power state to D1.", 
		"Power State 2 – sets a device’s power state to D2.", 
		"Power State 3 – sets a device’s power state to D3 (device off).", 
		"Power State Current – returns a device’s current power state.", 
		"Power State Dependencies – returns processor P-State dependencies.", 
		"Power State for Enumeration", 
		"Passive List – returns a list of passive cooling device objects.", 
		"Power Source – returns the power source device currently in use.", 
		"Performance Supported States – returns a list of supported processor performance states.", 
		"Passive – returns the passive trip point temperature.", 
		"Power State Wake – sets a device’s wake function.", 
		"Processor Throttling Control – returns throttling control and status registers.", 
		"Power Trip Points – sets trip points for the Power Meter device.", 
		"Prepare To Sleep – inform the platform of an impending sleep transition.", 
		"Processor Utilization Request – returns the number of processors that the platform would like to idle.", 
		"Proximity – returns a device’s proximity domain identifier.", 
		"Query – Embedded Controller query and SMBus Alarm control method.", 
		"Register Bit Offset – resource descriptor field.", 
		"Register Bit Width – resource descriptor field.", 
		"Resource Dependencies for Idle - returns the list of power resource dependencies for system level low power idle states.", 
		"Region – inform AML code of an operation region availability change.", 
		"Revision – returns the revision of the ACPI specification that is implemented.", 
		"Remove – returns a device’s removal ability status (docking).", 
		"Range – memory range type, resource descriptor field.", 
		"Read-Only Memory – returns a copy of the ROM data for a display device.", 
		"Device Reset   – executes a reset on the associated device or devices.", 
		"Resource Type – resource descriptor field.", 
		"Relative Temperature Values – returns temperature value information.", 
		"Read-Write Status – resource descriptor field.", 
		"Receive Buffer Size - Size of the receive buffer in a UART Serialbus connection, resource descriptor field.", 
		"S0 System State – returns values to enter the system into the S0 state.", 
		"S1 System State – returns values to enter the system into the S1 state.", 
		"S2 System State – returns values to enter the system into the S2 state.", 
		"S3 System State – returns values to enter the system into the S3 state.", 
		"S4 System State – returns values to enter the system into the S4 state.", 
		"S5 System State – returns values to enter the system into the S5 state.", 
		"S1 Device State – returns the highest D-state supported by a device when in the S1 state.", 
		"S2 Device State – returns the highest D-state supported by a device when in the S2 state.", 
		"S3 Device State – returns the highest D-state supported by a device when in the S3 state.", 
		"S4 Device State – returns the highest D-state supported by a device when in the S4 state.", 
		"S0 Device Wake State – returns the lowest D-state that the device can wake itself from S0.", 
		"S1 Device Wake State – returns the lowest D-state for this device that can wake the system from S1.", 
		"S2 Device Wake State – returns the lowest D-state for this device that can wake the system from S2.", 
		"S3 Device Wake State – returns the lowest D-state for this device that can wake the system from S3.", 
		"S4 Device Wake State – returns the lowest D-state for this device that can wake the system from S4.", 
		"System Bus – scope for device and bus objects.", 
		"Smart Battery Subsystem – returns the subsystem configuration.", 
		"Set Cooling Policy – sets the cooling policy (active or passive).", 
		"Set Device Data – sets data for a SATA device.", 
		"Segment – returns a device’s PCI Segment Group number.", 
		"Set Hardware Limit – sets the hardware limit enforced by the Power Meter.", 
		"Sharable – interrupt share status, resource descriptor field.", 
		"System Indicators – predefined scope.", 
		"Size – DMA transfer size, resource descriptor field.", 
		"System Locality Information – returns a list of NUMA system localities.", 
		"Slave Mode – Slave mode setting for a SerialBus connection, resource descriptor field.", 
		"Set Post Device – sets which video device will be posted at boot.", 
		"Connection Speed – Connection speed for a SerialBus connection, resource descriptor field", 
		"Set Resource Settings – sets a device’s resource allocation.", 
		"Set Real Time – Sets the current time to a Time and Alarm Control Method Device.", 
		"IPMI Spec Revision. See the Intelligent Platform Management Interface Specification at “Links to ACPI-Related Documents” (http://uefi.org/acpi) under the heading “Server Platform Management Interface Table”.", 
		"System Status – sets the system status indicator.", 
		"Status : (1) returns the current status of a device. (2) Returns the current on or off state of a Power Resource.", 
		"Stop Bits - Number of stop bits used in a UART SerialBus connection, resource descriptor field", 
		"Set Timing Mode – sets an IDE controller transfer timings.", 
		"Set Expired Timer Wake Policy – sets expired timer policies of the wake alarm device.", 
		"String – returns a device’s description string.", 
		"Set Timer Value – set timer values of the wake alarm device.", 
		"Supplies OSPM with the device’s Subsystem ID. Optional.", 
		"Slot User Number – returns the slot unique ID number.", 
		"System Wake Source – returns the source event that caused the system to wake.", 
		"Temporary – reserved for use by ASL compilers.", 
		"Thermal Constant 1 – returns TC1 for the passive cooling formula.", 
		"Thermal Constant 2 – returns TC2 for the passive cooling formula.", 
		"T-State Depth Limit – returns the _TSS entry number of the lowest power throttling state.", 
		"Thermal Fast Sampling Period - returns the thermal sampling period for passive cooling.", 
		"Expired Timer Wake Policy – returns timer policies of the wake alarm device.", 
		"Timer Values – returns remaining time of the wake alarm device.", 
		"Temperature – returns a thermal zone’s current temperature.", 
		"Throttling Present Capabilities – returns the current number of supported throttling states.", 
		"Trip Point Temperature – inform AML that a devices’ embedded temperature sensor has crossed a temperature trip point.", 
		"Translation – address translation offset, resource descriptor field.", 
		"Translation Sparse – sparse/dense flag, resource descriptor field.", 
		"Thermal Relationship Table – returns thermal relationships between platform devices.", 
		"Throttling State Dependencies – returns a list of T-state dependencies.", 
		"Type-Specific Flags – resource descriptor field.", 
		"Thermal Sensor Device - returns a reference to the thermal sensor reporting a zone temperature", 
		"Thermal Sampling Period – returns the thermal sampling period for passive cooling.", 
		"Throttling Supported States – returns supported throttling state information.", 
		"Temperature Sensor Threshold – returns the minimum separation for a device’s temperature trip points.", 
		"Translation Type – translation/static flag, resource descriptor field.", 
		"Transition To State – inform AML of an S-state transition.", 
		"Transmit Buffer Size – Size of the transmit buffer in a UART Serialbus connection, resource descriptor field", 
		"Type – DMA channel type (speed), resource descriptor field.", 
		"Thermal Zone – predefined scope: ACPI 1.0.", 
		"Thermal Zone Devices – returns a list of device names associated with a Thermal Zone.", 
		"Thermal Zone Member – returns a reference to the thermal zone of which a device is a member.", 
		"Thermal Zone Polling – returns a Thermal zone’s polling frequency.", 
		"Unique ID – return a device’s unique persistent ID.", 
		"USB Port Capabilities – returns a list of USB port capabilities.", 
		"User Presence Detect – returns user detection information.", 
		"User Presence Polling – returns the recommended user presence polling interval.", 
		"Vendor-defined Data – Vendor-defined data for a GPIO or SerialBus connection, resource descriptor field", 
		"Video Post Options – returns the implemented video post options.", 
		"Wake – inform AML that the system has just awakened.", 
		"Wireless Power Calibration - returns the notifier to wireless power controller.", 
		"Wireless Power Polling - returns the recommended polling frequency", 
		"Wake Event – method executed as a result of a wake event.", 
		"ACPI. Not declared in ACPI as a device. This ID is used by OSPM for the hardware resources consumed by the ACPI fixed register spaces, and the operation regions used by AML code. It represents the core ACPI hardware itself.", 
		"Generic Container Device. A device whose settings are totally controlled by its ACPI resource information, and otherwise needs no device or bus-specific driver support. This was originally known as Generic ISA Bus Device. This ID should only be used for containers that do not produce resources for consumption by child devices. Any system resources claimed by a PNP0A05 device’s _CRS object must be consumed by the container itself.", 
		"Generic Container Device. This device behaves exactly the same as the PNP0A05 device. This was originally known as Extended I/O Bus. This ID should only be used for containers that do not produce resources for consumption by child devices. Any system resources claimed by a PNP0A06 device’s _CRS object must be consumed by the container itself.", 
		"Embedded Controller Device. A host embedded controller controlled through an ACPI-aware driver.", 
		"Control Method Battery. A device that solely implements the ACPI Control Method Battery functions. A device that has some other primary function would use its normal device ID. This ID is used when the devices primary function is that of a battery.", 
		"Fan. A device that causes cooling when “on” (D0 device state).", 
		"Power Button Device. A device controlled through an ACPI-aware driver that provides power button functionality. This device is only needed if the power button is not supported using the fixed register space.", 
		"Lid Device. A device controlled through an ACPI-aware driver that provides lid status functionality. This device is only needed if the lid state is not supported using the fixed register space.", 
		"Sleep Button Device. A device controlled through an ACPI-aware driver that provides power button functionality. This device is optional.", 
		"PCI Interrupt Link Device. A device that allocates an interrupt connected to a PCI interrupt pin. See Section 6.2.13 for more details.", 
		"Memory Device. This device is a memory subsystem.", 
		"SMBus 1.0 Host Controller. An SMBus host controller (SMB-HC) compatible with the embedded controller-based SMB-HC interface (see Section 12.9), and implementing the SMBus 1.0 Specification.", 
		"Smart Battery Subsystem. The Smart battery Subsystem specified in Section 10, “Power Source Devices.”", 
		"Power Source Device. The Power Source device specified in Section 10, “Power Source Devices.” This can represent either an AC Adapter (on mobile platforms) or a fixed Power Supply.", 
		"Module Device. This device is a container object that acts as a bus node in a namespace. A Module Device without any of the _CRS, _PRS and _SRS methods behaves the same way as the Generic Container Devices (PNP0A05 or PNP0A06). If the Module Device contains a _CRS method, only these resources described in the _CRS are available for consumption by its child devices. Also, the Module Device can support _PRS and _SRS methods if _CRS is supported.", 
		"SMBus 2.0 Host Controller. An SMBus host controller (SMB-HC compatible with the embedded controller-based SMB-HC interface (see Section 12.9), and implementing the SMBus 2.0 Specification.", 
		"GPE Block Device. This device allows a system designer to describe GPE blocks beyond the two that are described in the FADT.", 
		"Processor Device. This device provides an alternative to declaring processors using the processor ASL statement. See Section 8.4 for more details.", 
		"Ambient Light Sensor Device. This device is an ambient light sensor. See Section 9.3.", 
		"I/OxAPIC Device. This device is an I/O unit that complies with both the APIC and SAPIC interrupt models.", 
		"I/O APIC Device. This device is an I/O unit that complies with the APIC interrupt model.", 
		"I/O SAPIC Device. This device is an I/O unit that complies with the SAPIC interrupt model.", 
		"Processor Aggregator Device. This device provides a control point for all processors in the platform. See Section 8.5.", 
		"Power Meter Device. This device is a power meter. See Section 10.4.", 
		"Time and Alarm Device. This device is a control method-based real-time clock and wake alarm. See Section 9.18.", 
		"User Presence Detection Device. This device senses user presence (proximity). See Section 9.16)", 
		"Processor container device. Used to declare hierarchical processor topologies (see Section 8.4.3, and Section 8.4.3.1).", 
		"Generic Buttons Device. This device reports button events corresponding to Human Interface Device (HID) control descriptors (see Section 9.19).", 
		"NVDIMM Root Device. This device contains the NVDIMM devices. See Section 9.20 and Table 5.107.", 
		"Generic Event Device. This device maps Interrupt-signaled events. See Section 5.6.9.", 
		"Wireless Power Calibration Device. This device uses user presence and notification.", 
		"USB4 host interface device. See Links to ACPI-Related Documents under the heading “USB4 Host Interface Specification”", 
		"Compute Express Link Host Bridge. This device is a Compute Express Link Host bridge."
		];
		
	for (let IndexVal =0 ; IndexVal < PreDefineName.length; IndexVal ++)
	{
		if (STxt.toUpperCase() == PreDefineName[IndexVal].toUpperCase())
		{
			if (PreDefNameHelpStr.length >= IndexVal)
			{
				return PreDefNameHelpStr[IndexVal];
			}
		}
	}
	
	return "";
}
// this method is called when your extension is deactivated
export function deactivate() {}
