---
name: ci

on:
  pull_request:
    branches:
      - master
      - main
      - develop
  push:
    branches:
      - master
      - main
      - develop
env:
  debug_ci: true
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, macos-14, macos-15, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Install Xvfb
        run: sudo apt-get update && sudo apt-get install -y xvfb
        if: ${{ runner.os == 'Linux' }}
      - name: Compile & Lint
        run: pnpm run pretest
      - name: Launch Xvfb
        run: |
          export DISPLAY=:99.0
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        if: ${{ runner.os == 'Linux' }}
      - name: Run tests
        run: pnpm run test
        env:
          DISPLAY: ${{ runner.os == 'Linux' && ':99.0' || '' }}
          DEBUG_CI: ${{ env.debug_ci == 'true' || runner.debug == '1' }}
      - name: Check for vsce
        run: which vsce || echo "vsce not found"
        if: ${{ env.debug_ci == 'true' && runner.os != 'Windows' }}
      - name: List files
        run: ls -lA
        if: ${{ env.debug_ci == 'true' && runner.os != 'Windows' }}
      - name: Install eza (Linux deb)
        run: sudo apt-get install -y eza
        if: ${{ env.debug_ci == 'true' && runner.os == 'Linux' }}
      - name: Install eza (macOS brew)
        run: brew install eza
        if: ${{ env.debug_ci == 'true' && runner.os == 'macOS' }}
      - name: List files in pretty print tree view
        run: eza --icons --color-scale --classify --git -la --header --tree --ignore-glob='.git'  --git-ignore --binary
        if: ${{ env.debug_ci == 'true' && runner.os != 'Windows' }}
